language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g grunt-cli
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt || grunt travisPullRequest' 
env:
  global:
  - secure: k2w01lXViIajvPWkrew0K+w5PS9/9KrCsqEmfg26qu9HfvIO2MUk4hFKZyQ101kjfGD3ro7FDlj97GZBNOO3KGCtQogrgADjWhzHvDdbu6OHMYH7FbIqa2RBf8/HgCQiTgLCTAlGYlUWX3QI6xK0rYc4EU5n3eqiRHsoWADgwGg=
  - secure: JBM+JdrAv0TduLSOdZ2yFSllWsAktlQlh99SMaWpTrlD4D+bkbEEdQbehY16a0NG67/g6HZsb5Nea6wwpRhv3xQatamDJHYP7Gm9KE2hObtFnoHvJ2v62ahuuQnQ486IHrvisIDDl/wvr+MFiKbaWTQqUc0TnoMDGMFP4O9H9+w=
